### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by nu8** [erlang/eep#12]
If I try to download a file, the average speed is 421k:

~~~
$ curl -O erlang.org/download/otp_win64_22.2.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 28 90.4M   28 25.7M    0     0   421k      0  0:03:39  0:01:02  0:02:37  433k
~~~

Files could be hosted here for faster speed:

<https://github.com/erlang/otp/releases>

**Comment by KennethL** [comment]
And when I do the same I get a factor 10 better download speed. So I
suppose it is about your location vs the servers location.
curl -O erlang.org/download/otp_win64_22.2.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100 90.4M  100 90.4M    0     0  4366k      0  0:00:21  0:00:21 --:--:--
4113k

Anyway we are investigating the possibilities to use github or other
solutions for this. Did not realize that is was so slow for some of you.
Is it consistently that slow for you and from where are you downloading?

/Kenneth, Erlang/OTP team

**Comment by nu8** [comment]
I am in Dallas. As can be seen, speed is fine for other domains:

~~~
$ curl -L -O https://github.com/mstorsjo/llvm-mingw/releases/download/20200325/llvm-mingw-20200325-x86_64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  164M  100  164M    0     0  5766k      0  0:00:29  0:00:29 --:--:-- 5874k
~~~

**Comment by KennethL** [comment]
The server is in Sweden so the bits have a long way to travel. But as said
we have this on the agenda.

/Kenneth

**Comment by garazdawi** [comment]
Closing this, you can follow the progress in https://bugs.erlang.org/browse/ERL-1222.

**Comment by nu8** [comment]
For anyone interested, the status hasnt changed at all on this since my original post:

~~~
PS D:\Desktop> curl.exe -O erlang.org/download/otp_win64_22.2.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 28 90.4M   28 25.6M    0     0   419k      0  0:03:40  0:01:02  0:02:38  426k
~~~

**Comment by garazdawi** [comment]
Since a couple of weeks ago you can download the windows releases and more from the github releases: https://github.com/erlang/otp/releases/tag/OTP-22.2
