### ISSUE TITLE
EEP-55's Backwards Compatibility

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/eep#19]
This is more of a question/request for guidance that an issue.

[EEP-55's Backwards Compatibility](https://github.com/erlang/eep/blob/master/eeps/eep-0055.md#backwards-compatibility) seems to refer to using old code on an Erlang/OTP version that already supports the pinning operator (e.g. OTP 24, 25, ...).

I'm wondering how we'd be able to use new code that uses it in older Erlang/OTP-supported software (e.g. OTP 19, 20, ...). Would a parse transform of any kind be possible, here?

Thanks.

**Comment by garazdawi** [comment]
Hello!

This is a question better asked of the EEP author, so take this to the mailing list or the PR associated with the EEP.

Lukas
