### ISSUE TITLE
Licensing problem

### ISSUE THREAD

**Issue by hauleth** [erlang/eep#25]
## DISCLAIMER

I am not a lawyer and all I have written there is about my limited knowledge and what I have found on the internet. It will require some professional lawyer insights.

---

Right now we are using copyright footer in form of:

```markdown
Copyright
=========

This document has been placed in the public domain.
```

However "public domain" isn't something that exists in many jurisdictions (on CC mailing list there is information that it didn't existed [in Sweden](https://cc-licenses.ibiblio.narkive.com/dARP9u6Q/public-domain-in-sweden#post2) in 2007), and other jurisdictions do not allow to voluntary give up your copyright to the PD. This mean that this clause can be void sometimes, and that can be a threat to the Erlang community. I think that we should contact some lawyers that specialise in copyrights and validate whether we can and should use such disclaimer or maybe we should require some more detailed licensing there (like CC0 or BSD-0).

**Comment by lhoguin** [comment]
For what it's worth, in France you cannot voluntarily place a piece of work in the public domain because you cannot give up your moral right over it. Whether an EEP is considered a piece of work in that regard is another question entirely, though.

Changing to CC0 by default would probably be better.

**Comment by garazdawi** [comment]
I believe we have taken the template from the Python PEP documents that use the same wording. Maybe they have had a similar discussion and have some more information?

**Comment by lhoguin** [comment]
Their template now says:

```
This document is placed in the public domain or under the CC0-1.0-Universal license, whichever is more permissive.
```

https://www.python.org/dev/peps/pep-0012/

I guess they did have a similar discussion.

**Comment by KennethL** [comment]
I will check with our legal department.

**Comment by KennethL** [comment]
Our legal department says that in practice there is no issue but it is a good idea to change it to CC0, from now on (no need to change old EEPs). So I have decided to follow the Python example and update the instructions to say:

This document is placed in the public domain or under the CC0-1.0-Universal license, whichever is more permissive.
