### ISSUE TITLE
EEP48, EEP 58 and EEP 61 are outdated

### ISSUE THREAD

**Issue by williamthome** [erlang/eep#48]
The following EEPs are outdated:
- [EEP 48: Documentation storage and format](https://www.erlang.org/eeps/eep-0048.html): it's in draft and standards track, but the docs says [EDoc implements EEP-48](https://www.erlang.org/doc/apps/edoc/chapter.html#doc-chunks);
- [EEP 58: Map Comprehension](https://github.com/erlang/eep/pull/32): stills on the standards track but the feature is in OTP 26;
- [EEP 61: Built-in dynamic type](https://github.com/erlang/eep/pull/44): same as EEP 58.

**Comment by RaimoNiskanen** [comment]
@williamthome: Does PR #52 seem right to you?

**Comment by williamthome** [comment]
Thanks, @RaimoNiskanen.
