### ISSUE TITLE
Status of the EEP 18: JSON bifs 

### ISSUE THREAD

**Issue by williamthome** [erlang/eep#61]
The [EEP 18: JSON bifs](https://www.erlang.org/eeps/eep-0018) proposes `term_to_json` and `json_to_term`, but [EEP 68: JSON library](https://www.erlang.org/eeps/eep-0068) introduced the `json` module into OTP 27.

Should `EEP 18` be defined with another status? Looking at the [EEP legend](https://www.erlang.org/eeps), it may be defined as rejected or withdrawn.

**Comment by michalmuskala** [comment]
There's also the "replaced by another EEP" status, that might be applicable here, but yes, I agree it would make sense to normalise it somehow.

**Comment by kikofernandez** [comment]
Thanks, I will fix this. I will close once fixed

**Comment by kikofernandez** [comment]
Hej! I think the replaced-by and replaces makes sense here, so I updated the EEPs with those.
Thanks for reporting and sorry for not seeing this before.
Feel free to always ping me :) but I will keep an eye in the future
