### ISSUE TITLE
Strange "Warnings" box in the footer of EEP-0

### ISSUE THREAD

**Issue by Maria-12648430** [erlang/eep#66]
There is a [strange box labeled "Warnings #"](https://www.erlang.org/eeps/eep-0000#warnings) in (actually, below) the footer of [EEP-0](https://www.erlang.org/eeps/eep-0000).

![grafik](https://github.com/user-attachments/assets/a7523437-d140-4044-8086-42d4a8073d8c)

**Comment by garazdawi** [comment]
These warnings are reported by https://github.com/erlang/eep/blob/master/eep-index.pl, seems like those EEPs use status fields that are not allowed.

I've moved the issue to the eep repo to track it from there.
