### ISSUE TITLE
Windows zip release

### ISSUE THREAD

**Issue by cup** [erlang/eep#8]
If you go here:

https://github.com/erlang/otp/releases

You see EXE installer for Windows. This contrasts with other programming
languages that offer both an executable installer and ZIP files that can be
extracted and run. For example Go:

https://golang.org/dl

and Nim:

https://nim-lang.org/install_windows.html

Python:

https://python.org/downloads/release/python-373

and C#:

https://dotnet.microsoft.com/download/dotnet-core/2.2

PHP:

https://windows.php.net/download

Perl:

http://strawberryperl.com/releases.html

**Comment by garazdawi** [comment]
What about https://www.erlang.org/downloads?

**Comment by cup** [comment]
@garazdawi those are EXE files...

**Comment by garazdawi** [comment]
Sorry, read your issue too quick.

This is not the right place to discuss this. Pleace open an issue at bugs.erlang.org.

**Comment by nu8** [comment]
https://bugs.erlang.org/browse/ERL-1252
